# Yarn Berry (v2+) configuration file
# This file is used to configure Yarn package manager

# Use node_modules linker (compatible with most tools)
nodeLinker: node-modules

# Enable zero-installs (optional - uncomment to enable)
# enableZeroInstalls: true

# Ignore scripts for security (optional)
# ignoreScripts: false

# Registry settings (use default npm registry)
# npmRegistryServer: "https://registry.npmjs.org/"

# Compression level for cache
compressionLevel: mixed

